//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BeneficiariosDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiariosDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoTipoBeneficiario" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoTipoBeneficiario"/&gt;
 *         &lt;element name="tipoTipoDocumento" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoTipoDocumento" minOccurs="0"/&gt;
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoPrimerApellido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoSegundoApellido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoPrimerNombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoSegundoNombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoGenero" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoGenero" minOccurs="0"/&gt;
 *         &lt;element name="tipoFechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="tipoIndEstudiaAct" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoIndEstudiaAct" minOccurs="0"/&gt;
 *         &lt;element name="tipoIndDependeEco" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoIndDependeEco" minOccurs="0"/&gt;
 *         &lt;element name="tipoEstadoExpedicion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoEstadoExpedicion" minOccurs="0"/&gt;
 *         &lt;element name="tipoEstadoActual" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TipoEstadoActual" minOccurs="0"/&gt;
 *         &lt;element name="temporBeneficiario" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}TemporBeneficiario" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiariosDTO", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", propOrder = {
    "tipoTipoBeneficiario",
    "tipoTipoDocumento",
    "tipoDocumento",
    "tipoPrimerApellido",
    "tipoSegundoApellido",
    "tipoPrimerNombre",
    "tipoSegundoNombre",
    "tipoGenero",
    "tipoFechaNacimiento",
    "tipoIndEstudiaAct",
    "tipoIndDependeEco",
    "tipoEstadoExpedicion",
    "tipoEstadoActual",
    "temporBeneficiario"
})
public class BeneficiariosDTO {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoTipoBeneficiario tipoTipoBeneficiario;
    @XmlElementRef(name = "tipoTipoDocumento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoTipoDocumento> tipoTipoDocumento;
    @XmlElementRef(name = "tipoDocumento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoDocumento;
    @XmlElementRef(name = "tipoPrimerApellido", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoPrimerApellido;
    @XmlElementRef(name = "tipoSegundoApellido", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoSegundoApellido;
    @XmlElementRef(name = "tipoPrimerNombre", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoPrimerNombre;
    @XmlElementRef(name = "tipoSegundoNombre", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoSegundoNombre;
    @XmlElementRef(name = "tipoGenero", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoGenero> tipoGenero;
    @XmlElementRef(name = "tipoFechaNacimiento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> tipoFechaNacimiento;
    @XmlElementRef(name = "tipoIndEstudiaAct", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoIndEstudiaAct> tipoIndEstudiaAct;
    @XmlElementRef(name = "tipoIndDependeEco", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoIndDependeEco> tipoIndDependeEco;
    @XmlElementRef(name = "tipoEstadoExpedicion", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoEstadoExpedicion> tipoEstadoExpedicion;
    @XmlElementRef(name = "tipoEstadoActual", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoEstadoActual> tipoEstadoActual;
    @XmlElementRef(name = "temporBeneficiario", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TemporBeneficiario> temporBeneficiario;

    /**
     * Gets the value of the tipoTipoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTipoBeneficiario }
     *     
     */
    public TipoTipoBeneficiario getTipoTipoBeneficiario() {
        return tipoTipoBeneficiario;
    }

    /**
     * Sets the value of the tipoTipoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTipoBeneficiario }
     *     
     */
    public void setTipoTipoBeneficiario(TipoTipoBeneficiario value) {
        this.tipoTipoBeneficiario = value;
    }

    /**
     * Gets the value of the tipoTipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoTipoDocumento }{@code >}
     *     
     */
    public JAXBElement<TipoTipoDocumento> getTipoTipoDocumento() {
        return tipoTipoDocumento;
    }

    /**
     * Sets the value of the tipoTipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoTipoDocumento }{@code >}
     *     
     */
    public void setTipoTipoDocumento(JAXBElement<TipoTipoDocumento> value) {
        this.tipoTipoDocumento = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoDocumento(JAXBElement<String> value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the tipoPrimerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoPrimerApellido() {
        return tipoPrimerApellido;
    }

    /**
     * Sets the value of the tipoPrimerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoPrimerApellido(JAXBElement<String> value) {
        this.tipoPrimerApellido = value;
    }

    /**
     * Gets the value of the tipoSegundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoSegundoApellido() {
        return tipoSegundoApellido;
    }

    /**
     * Sets the value of the tipoSegundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoSegundoApellido(JAXBElement<String> value) {
        this.tipoSegundoApellido = value;
    }

    /**
     * Gets the value of the tipoPrimerNombre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoPrimerNombre() {
        return tipoPrimerNombre;
    }

    /**
     * Sets the value of the tipoPrimerNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoPrimerNombre(JAXBElement<String> value) {
        this.tipoPrimerNombre = value;
    }

    /**
     * Gets the value of the tipoSegundoNombre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoSegundoNombre() {
        return tipoSegundoNombre;
    }

    /**
     * Sets the value of the tipoSegundoNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoSegundoNombre(JAXBElement<String> value) {
        this.tipoSegundoNombre = value;
    }

    /**
     * Gets the value of the tipoGenero property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoGenero }{@code >}
     *     
     */
    public JAXBElement<TipoGenero> getTipoGenero() {
        return tipoGenero;
    }

    /**
     * Sets the value of the tipoGenero property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoGenero }{@code >}
     *     
     */
    public void setTipoGenero(JAXBElement<TipoGenero> value) {
        this.tipoGenero = value;
    }

    /**
     * Gets the value of the tipoFechaNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTipoFechaNacimiento() {
        return tipoFechaNacimiento;
    }

    /**
     * Sets the value of the tipoFechaNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTipoFechaNacimiento(JAXBElement<XMLGregorianCalendar> value) {
        this.tipoFechaNacimiento = value;
    }

    /**
     * Gets the value of the tipoIndEstudiaAct property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoIndEstudiaAct }{@code >}
     *     
     */
    public JAXBElement<TipoIndEstudiaAct> getTipoIndEstudiaAct() {
        return tipoIndEstudiaAct;
    }

    /**
     * Sets the value of the tipoIndEstudiaAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoIndEstudiaAct }{@code >}
     *     
     */
    public void setTipoIndEstudiaAct(JAXBElement<TipoIndEstudiaAct> value) {
        this.tipoIndEstudiaAct = value;
    }

    /**
     * Gets the value of the tipoIndDependeEco property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoIndDependeEco }{@code >}
     *     
     */
    public JAXBElement<TipoIndDependeEco> getTipoIndDependeEco() {
        return tipoIndDependeEco;
    }

    /**
     * Sets the value of the tipoIndDependeEco property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoIndDependeEco }{@code >}
     *     
     */
    public void setTipoIndDependeEco(JAXBElement<TipoIndDependeEco> value) {
        this.tipoIndDependeEco = value;
    }

    /**
     * Gets the value of the tipoEstadoExpedicion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoEstadoExpedicion }{@code >}
     *     
     */
    public JAXBElement<TipoEstadoExpedicion> getTipoEstadoExpedicion() {
        return tipoEstadoExpedicion;
    }

    /**
     * Sets the value of the tipoEstadoExpedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoEstadoExpedicion }{@code >}
     *     
     */
    public void setTipoEstadoExpedicion(JAXBElement<TipoEstadoExpedicion> value) {
        this.tipoEstadoExpedicion = value;
    }

    /**
     * Gets the value of the tipoEstadoActual property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoEstadoActual }{@code >}
     *     
     */
    public JAXBElement<TipoEstadoActual> getTipoEstadoActual() {
        return tipoEstadoActual;
    }

    /**
     * Sets the value of the tipoEstadoActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoEstadoActual }{@code >}
     *     
     */
    public void setTipoEstadoActual(JAXBElement<TipoEstadoActual> value) {
        this.tipoEstadoActual = value;
    }

    /**
     * Gets the value of the temporBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TemporBeneficiario }{@code >}
     *     
     */
    public JAXBElement<TemporBeneficiario> getTemporBeneficiario() {
        return temporBeneficiario;
    }

    /**
     * Sets the value of the temporBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TemporBeneficiario }{@code >}
     *     
     */
    public void setTemporBeneficiario(JAXBElement<TemporBeneficiario> value) {
        this.temporBeneficiario = value;
    }

}
