//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CausanteDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CausanteDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoIdentificacion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO}TipoIdentificacion"/&gt;
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoPrimerApellido" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoSegundoApellido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoPrimerNombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoSegundoNombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoGenero" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO}TipoGenero"/&gt;
 *         &lt;element name="tipoFechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="tipoEstadoExpedicion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO}TipoEstadoExpedicion"/&gt;
 *         &lt;element name="tipoEstadoActual" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO}TipoEstadoActual"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CausanteDTO", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", propOrder = {
    "tipoIdentificacion",
    "tipoDocumento",
    "tipoPrimerApellido",
    "tipoSegundoApellido",
    "tipoPrimerNombre",
    "tipoSegundoNombre",
    "tipoGenero",
    "tipoFechaNacimiento",
    "tipoEstadoExpedicion",
    "tipoEstadoActual"
})
public class CausanteDTO {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoIdentificacion tipoIdentificacion;
    @XmlElement(required = true)
    protected String tipoDocumento;
    @XmlElement(required = true)
    protected String tipoPrimerApellido;
    @XmlElementRef(name = "tipoSegundoApellido", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoSegundoApellido;
    @XmlElement(required = true)
    protected String tipoPrimerNombre;
    @XmlElementRef(name = "tipoSegundoNombre", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoSegundoNombre;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoGenero2 tipoGenero;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tipoFechaNacimiento;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoEstadoExpedicion2 tipoEstadoExpedicion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoEstadoActual2 tipoEstadoActual;

    /**
     * Gets the value of the tipoIdentificacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacion }
     *     
     */
    public TipoIdentificacion getTipoIdentificacion() {
        return tipoIdentificacion;
    }

    /**
     * Sets the value of the tipoIdentificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacion }
     *     
     */
    public void setTipoIdentificacion(TipoIdentificacion value) {
        this.tipoIdentificacion = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the tipoPrimerApellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPrimerApellido() {
        return tipoPrimerApellido;
    }

    /**
     * Sets the value of the tipoPrimerApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPrimerApellido(String value) {
        this.tipoPrimerApellido = value;
    }

    /**
     * Gets the value of the tipoSegundoApellido property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoSegundoApellido() {
        return tipoSegundoApellido;
    }

    /**
     * Sets the value of the tipoSegundoApellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoSegundoApellido(JAXBElement<String> value) {
        this.tipoSegundoApellido = value;
    }

    /**
     * Gets the value of the tipoPrimerNombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPrimerNombre() {
        return tipoPrimerNombre;
    }

    /**
     * Sets the value of the tipoPrimerNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPrimerNombre(String value) {
        this.tipoPrimerNombre = value;
    }

    /**
     * Gets the value of the tipoSegundoNombre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoSegundoNombre() {
        return tipoSegundoNombre;
    }

    /**
     * Sets the value of the tipoSegundoNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoSegundoNombre(JAXBElement<String> value) {
        this.tipoSegundoNombre = value;
    }

    /**
     * Gets the value of the tipoGenero property.
     * 
     * @return
     *     possible object is
     *     {@link TipoGenero2 }
     *     
     */
    public TipoGenero2 getTipoGenero() {
        return tipoGenero;
    }

    /**
     * Sets the value of the tipoGenero property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoGenero2 }
     *     
     */
    public void setTipoGenero(TipoGenero2 value) {
        this.tipoGenero = value;
    }

    /**
     * Gets the value of the tipoFechaNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTipoFechaNacimiento() {
        return tipoFechaNacimiento;
    }

    /**
     * Sets the value of the tipoFechaNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTipoFechaNacimiento(XMLGregorianCalendar value) {
        this.tipoFechaNacimiento = value;
    }

    /**
     * Gets the value of the tipoEstadoExpedicion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoEstadoExpedicion2 }
     *     
     */
    public TipoEstadoExpedicion2 getTipoEstadoExpedicion() {
        return tipoEstadoExpedicion;
    }

    /**
     * Sets the value of the tipoEstadoExpedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoEstadoExpedicion2 }
     *     
     */
    public void setTipoEstadoExpedicion(TipoEstadoExpedicion2 value) {
        this.tipoEstadoExpedicion = value;
    }

    /**
     * Gets the value of the tipoEstadoActual property.
     * 
     * @return
     *     possible object is
     *     {@link TipoEstadoActual2 }
     *     
     */
    public TipoEstadoActual2 getTipoEstadoActual() {
        return tipoEstadoActual;
    }

    /**
     * Sets the value of the tipoEstadoActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoEstadoActual2 }
     *     
     */
    public void setTipoEstadoActual(TipoEstadoActual2 value) {
        this.tipoEstadoActual = value;
    }

}
