//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NovedadRentaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NovedadRentaDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoNovedad" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO}TipoNovedad"/&gt;
 *         &lt;element name="tipoTipoDocumento" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO}TipoTipoDocumento" minOccurs="0"/&gt;
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipoFechaNovedad" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="tipoValorMesada" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="tipoNumeroMesadas" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="docSoporteNovedad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoBeneficiario" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO}BeneficiariosDTO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NovedadRentaDTO", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", propOrder = {
    "tipoNovedad",
    "tipoTipoDocumento",
    "tipoDocumento",
    "tipoFechaNovedad",
    "tipoValorMesada",
    "tipoNumeroMesadas",
    "docSoporteNovedad",
    "tipoBeneficiario"
})
public class NovedadRentaDTO {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoNovedad tipoNovedad;
    @XmlElementRef(name = "tipoTipoDocumento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<TipoTipoDocumento2> tipoTipoDocumento;
    @XmlElementRef(name = "tipoDocumento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tipoDocumento;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tipoFechaNovedad;
    @XmlElementRef(name = "tipoValorMesada", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> tipoValorMesada;
    @XmlElementRef(name = "tipoNumeroMesadas", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> tipoNumeroMesadas;
    @XmlElement(required = true)
    protected String docSoporteNovedad;
    @XmlElementRef(name = "tipoBeneficiario", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<BeneficiariosDTO> tipoBeneficiario;

    /**
     * Gets the value of the tipoNovedad property.
     * 
     * @return
     *     possible object is
     *     {@link TipoNovedad }
     *     
     */
    public TipoNovedad getTipoNovedad() {
        return tipoNovedad;
    }

    /**
     * Sets the value of the tipoNovedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoNovedad }
     *     
     */
    public void setTipoNovedad(TipoNovedad value) {
        this.tipoNovedad = value;
    }

    /**
     * Gets the value of the tipoTipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TipoTipoDocumento2 }{@code >}
     *     
     */
    public JAXBElement<TipoTipoDocumento2> getTipoTipoDocumento() {
        return tipoTipoDocumento;
    }

    /**
     * Sets the value of the tipoTipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TipoTipoDocumento2 }{@code >}
     *     
     */
    public void setTipoTipoDocumento(JAXBElement<TipoTipoDocumento2> value) {
        this.tipoTipoDocumento = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTipoDocumento(JAXBElement<String> value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the tipoFechaNovedad property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTipoFechaNovedad() {
        return tipoFechaNovedad;
    }

    /**
     * Sets the value of the tipoFechaNovedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTipoFechaNovedad(XMLGregorianCalendar value) {
        this.tipoFechaNovedad = value;
    }

    /**
     * Gets the value of the tipoValorMesada property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTipoValorMesada() {
        return tipoValorMesada;
    }

    /**
     * Sets the value of the tipoValorMesada property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setTipoValorMesada(JAXBElement<BigDecimal> value) {
        this.tipoValorMesada = value;
    }

    /**
     * Gets the value of the tipoNumeroMesadas property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getTipoNumeroMesadas() {
        return tipoNumeroMesadas;
    }

    /**
     * Sets the value of the tipoNumeroMesadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setTipoNumeroMesadas(JAXBElement<Integer> value) {
        this.tipoNumeroMesadas = value;
    }

    /**
     * Gets the value of the docSoporteNovedad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocSoporteNovedad() {
        return docSoporteNovedad;
    }

    /**
     * Sets the value of the docSoporteNovedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocSoporteNovedad(String value) {
        this.docSoporteNovedad = value;
    }

    /**
     * Gets the value of the tipoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BeneficiariosDTO }{@code >}
     *     
     */
    public JAXBElement<BeneficiariosDTO> getTipoBeneficiario() {
        return tipoBeneficiario;
    }

    /**
     * Sets the value of the tipoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BeneficiariosDTO }{@code >}
     *     
     */
    public void setTipoBeneficiario(JAXBElement<BeneficiariosDTO> value) {
        this.tipoBeneficiario = value;
    }

}
