//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bbva.obp.SolicitudRentas.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExcepcionBonosPensionales_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "ExcepcionBonosPensionales");
    private final static QName _RegistroDocumentoElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroDocumentoElement");
    private final static QName _RegistroDocumentoResponseElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroDocumentoResponseElement");
    private final static QName _RegistroSolicitudRentaElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroSolicitudRentaElement");
    private final static QName _RegistroSolicitudRentaResponseElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroSolicitudRentaResponseElement");
    private final static QName _RegistroNovedadElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroNovedadElement");
    private final static QName _RegistroNovedadResponseElement_QNAME = new QName("http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", "registroNovedadResponseElement");
    private final static QName _RegistroDocumentosTipoIdentificacionB_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroDocumentos", "tipoIdentificacionB");
    private final static QName _RegistroDocumentosTipoDocumentoB_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroDocumentos", "tipoDocumentoB");
    private final static QName _RentaDTOTipoFechaInicioRenDif_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", "tipoFechaInicioRenDif");
    private final static QName _RentaDTODocSoporteJudicial_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", "docSoporteJudicial");
    private final static QName _RentaDTOFechaDocSopteJud_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", "fechaDocSopteJud");
    private final static QName _RentaDTOObservacionesFalloJud_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", "observacionesFalloJud");
    private final static QName _CausanteDTOTipoSegundoApellido_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", "tipoSegundoApellido");
    private final static QName _CausanteDTOTipoSegundoNombre_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", "tipoSegundoNombre");
    private final static QName _NovedadRentaDTOTipoTipoDocumento_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", "tipoTipoDocumento");
    private final static QName _NovedadRentaDTOTipoDocumento_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", "tipoDocumento");
    private final static QName _NovedadRentaDTOTipoValorMesada_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", "tipoValorMesada");
    private final static QName _NovedadRentaDTOTipoNumeroMesadas_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", "tipoNumeroMesadas");
    private final static QName _NovedadRentaDTOTipoBeneficiario_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", "tipoBeneficiario");
    private final static QName _BeneficiariosDTOTipoTipoDocumento_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoTipoDocumento");
    private final static QName _BeneficiariosDTOTipoDocumento_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoDocumento");
    private final static QName _BeneficiariosDTOTipoPrimerApellido_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoPrimerApellido");
    private final static QName _BeneficiariosDTOTipoSegundoApellido_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoSegundoApellido");
    private final static QName _BeneficiariosDTOTipoPrimerNombre_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoPrimerNombre");
    private final static QName _BeneficiariosDTOTipoSegundoNombre_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoSegundoNombre");
    private final static QName _BeneficiariosDTOTipoGenero_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoGenero");
    private final static QName _BeneficiariosDTOTipoFechaNacimiento_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoFechaNacimiento");
    private final static QName _BeneficiariosDTOTipoIndEstudiaAct_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoIndEstudiaAct");
    private final static QName _BeneficiariosDTOTipoIndDependeEco_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoIndDependeEco");
    private final static QName _BeneficiariosDTOTipoEstadoExpedicion_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoEstadoExpedicion");
    private final static QName _BeneficiariosDTOTipoEstadoActual_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "tipoEstadoActual");
    private final static QName _BeneficiariosDTOTemporBeneficiario_QNAME = new QName("http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", "temporBeneficiario");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bbva.obp.SolicitudRentas.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BeneficiariosDTO }
     * 
     */
    public BeneficiariosDTO createBeneficiariosDTO() {
        return new BeneficiariosDTO();
    }

    /**
     * Create an instance of {@link NovedadRentaDTO }
     * 
     */
    public NovedadRentaDTO createNovedadRentaDTO() {
        return new NovedadRentaDTO();
    }

    /**
     * Create an instance of {@link SolicitudRenta }
     * 
     */
    public SolicitudRenta createSolicitudRenta() {
        return new SolicitudRenta();
    }

    /**
     * Create an instance of {@link CausanteDTO }
     * 
     */
    public CausanteDTO createCausanteDTO() {
        return new CausanteDTO();
    }

    /**
     * Create an instance of {@link RentaDTO }
     * 
     */
    public RentaDTO createRentaDTO() {
        return new RentaDTO();
    }

    /**
     * Create an instance of {@link RegistroDocumentos }
     * 
     */
    public RegistroDocumentos createRegistroDocumentos() {
        return new RegistroDocumentos();
    }

    /**
     * Create an instance of {@link RegistroNovedad }
     * 
     */
    public RegistroNovedad createRegistroNovedad() {
        return new RegistroNovedad();
    }

    /**
     * Create an instance of {@link ExcepcionBonosPensionales }
     * 
     */
    public ExcepcionBonosPensionales createExcepcionBonosPensionales() {
        return new ExcepcionBonosPensionales();
    }

    /**
     * Create an instance of {@link ResultadoDTO }
     * 
     */
    public ResultadoDTO createResultadoDTO() {
        return new ResultadoDTO();
    }

    /**
     * Create an instance of {@link TipoCodigoTransaccionE }
     * 
     */
    public TipoCodigoTransaccionE createTipoCodigoTransaccionE() {
        return new TipoCodigoTransaccionE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExcepcionBonosPensionales }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExcepcionBonosPensionales }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "ExcepcionBonosPensionales")
    public JAXBElement<ExcepcionBonosPensionales> createExcepcionBonosPensionales(ExcepcionBonosPensionales value) {
        return new JAXBElement<ExcepcionBonosPensionales>(_ExcepcionBonosPensionales_QNAME, ExcepcionBonosPensionales.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistroDocumentos }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegistroDocumentos }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroDocumentoElement")
    public JAXBElement<RegistroDocumentos> createRegistroDocumentoElement(RegistroDocumentos value) {
        return new JAXBElement<RegistroDocumentos>(_RegistroDocumentoElement_QNAME, RegistroDocumentos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroDocumentoResponseElement")
    public JAXBElement<ResultadoDTO> createRegistroDocumentoResponseElement(ResultadoDTO value) {
        return new JAXBElement<ResultadoDTO>(_RegistroDocumentoResponseElement_QNAME, ResultadoDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitudRenta }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SolicitudRenta }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroSolicitudRentaElement")
    public JAXBElement<SolicitudRenta> createRegistroSolicitudRentaElement(SolicitudRenta value) {
        return new JAXBElement<SolicitudRenta>(_RegistroSolicitudRentaElement_QNAME, SolicitudRenta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroSolicitudRentaResponseElement")
    public JAXBElement<ResultadoDTO> createRegistroSolicitudRentaResponseElement(ResultadoDTO value) {
        return new JAXBElement<ResultadoDTO>(_RegistroSolicitudRentaResponseElement_QNAME, ResultadoDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistroNovedad }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegistroNovedad }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroNovedadElement")
    public JAXBElement<RegistroNovedad> createRegistroNovedadElement(RegistroNovedad value) {
        return new JAXBElement<RegistroNovedad>(_RegistroNovedadElement_QNAME, RegistroNovedad.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResultadoDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicioaseguradora.servicios.webservices.bonospensionales.minhacienda.gov.co/", name = "registroNovedadResponseElement")
    public JAXBElement<ResultadoDTO> createRegistroNovedadResponseElement(ResultadoDTO value) {
        return new JAXBElement<ResultadoDTO>(_RegistroNovedadResponseElement_QNAME, ResultadoDTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdentificacionB }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoIdentificacionB }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroDocumentos", name = "tipoIdentificacionB", scope = RegistroDocumentos.class)
    public JAXBElement<TipoIdentificacionB> createRegistroDocumentosTipoIdentificacionB(TipoIdentificacionB value) {
        return new JAXBElement<TipoIdentificacionB>(_RegistroDocumentosTipoIdentificacionB_QNAME, TipoIdentificacionB.class, RegistroDocumentos.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroDocumentos", name = "tipoDocumentoB", scope = RegistroDocumentos.class)
    public JAXBElement<String> createRegistroDocumentosTipoDocumentoB(String value) {
        return new JAXBElement<String>(_RegistroDocumentosTipoDocumentoB_QNAME, String.class, RegistroDocumentos.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", name = "tipoFechaInicioRenDif", scope = RentaDTO.class)
    public JAXBElement<XMLGregorianCalendar> createRentaDTOTipoFechaInicioRenDif(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RentaDTOTipoFechaInicioRenDif_QNAME, XMLGregorianCalendar.class, RentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", name = "docSoporteJudicial", scope = RentaDTO.class)
    public JAXBElement<String> createRentaDTODocSoporteJudicial(String value) {
        return new JAXBElement<String>(_RentaDTODocSoporteJudicial_QNAME, String.class, RentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", name = "fechaDocSopteJud", scope = RentaDTO.class)
    public JAXBElement<XMLGregorianCalendar> createRentaDTOFechaDocSopteJud(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RentaDTOFechaDocSopteJud_QNAME, XMLGregorianCalendar.class, RentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", name = "observacionesFalloJud", scope = RentaDTO.class)
    public JAXBElement<String> createRentaDTOObservacionesFalloJud(String value) {
        return new JAXBElement<String>(_RentaDTOObservacionesFalloJud_QNAME, String.class, RentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", name = "tipoSegundoApellido", scope = CausanteDTO.class)
    public JAXBElement<String> createCausanteDTOTipoSegundoApellido(String value) {
        return new JAXBElement<String>(_CausanteDTOTipoSegundoApellido_QNAME, String.class, CausanteDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/CausanteDTO", name = "tipoSegundoNombre", scope = CausanteDTO.class)
    public JAXBElement<String> createCausanteDTOTipoSegundoNombre(String value) {
        return new JAXBElement<String>(_CausanteDTOTipoSegundoNombre_QNAME, String.class, CausanteDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoTipoDocumento2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoTipoDocumento2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", name = "tipoTipoDocumento", scope = NovedadRentaDTO.class)
    public JAXBElement<TipoTipoDocumento2> createNovedadRentaDTOTipoTipoDocumento(TipoTipoDocumento2 value) {
        return new JAXBElement<TipoTipoDocumento2>(_NovedadRentaDTOTipoTipoDocumento_QNAME, TipoTipoDocumento2 .class, NovedadRentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", name = "tipoDocumento", scope = NovedadRentaDTO.class)
    public JAXBElement<String> createNovedadRentaDTOTipoDocumento(String value) {
        return new JAXBElement<String>(_NovedadRentaDTOTipoDocumento_QNAME, String.class, NovedadRentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", name = "tipoValorMesada", scope = NovedadRentaDTO.class)
    public JAXBElement<BigDecimal> createNovedadRentaDTOTipoValorMesada(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NovedadRentaDTOTipoValorMesada_QNAME, BigDecimal.class, NovedadRentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", name = "tipoNumeroMesadas", scope = NovedadRentaDTO.class)
    public JAXBElement<Integer> createNovedadRentaDTOTipoNumeroMesadas(Integer value) {
        return new JAXBElement<Integer>(_NovedadRentaDTOTipoNumeroMesadas_QNAME, Integer.class, NovedadRentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeneficiariosDTO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BeneficiariosDTO }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO", name = "tipoBeneficiario", scope = NovedadRentaDTO.class)
    public JAXBElement<BeneficiariosDTO> createNovedadRentaDTOTipoBeneficiario(BeneficiariosDTO value) {
        return new JAXBElement<BeneficiariosDTO>(_NovedadRentaDTOTipoBeneficiario_QNAME, BeneficiariosDTO.class, NovedadRentaDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoTipoDocumento }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoTipoDocumento }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoTipoDocumento", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoTipoDocumento> createBeneficiariosDTOTipoTipoDocumento(TipoTipoDocumento value) {
        return new JAXBElement<TipoTipoDocumento>(_BeneficiariosDTOTipoTipoDocumento_QNAME, TipoTipoDocumento.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoDocumento", scope = BeneficiariosDTO.class)
    public JAXBElement<String> createBeneficiariosDTOTipoDocumento(String value) {
        return new JAXBElement<String>(_BeneficiariosDTOTipoDocumento_QNAME, String.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoPrimerApellido", scope = BeneficiariosDTO.class)
    public JAXBElement<String> createBeneficiariosDTOTipoPrimerApellido(String value) {
        return new JAXBElement<String>(_BeneficiariosDTOTipoPrimerApellido_QNAME, String.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoSegundoApellido", scope = BeneficiariosDTO.class)
    public JAXBElement<String> createBeneficiariosDTOTipoSegundoApellido(String value) {
        return new JAXBElement<String>(_BeneficiariosDTOTipoSegundoApellido_QNAME, String.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoPrimerNombre", scope = BeneficiariosDTO.class)
    public JAXBElement<String> createBeneficiariosDTOTipoPrimerNombre(String value) {
        return new JAXBElement<String>(_BeneficiariosDTOTipoPrimerNombre_QNAME, String.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoSegundoNombre", scope = BeneficiariosDTO.class)
    public JAXBElement<String> createBeneficiariosDTOTipoSegundoNombre(String value) {
        return new JAXBElement<String>(_BeneficiariosDTOTipoSegundoNombre_QNAME, String.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoGenero }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoGenero }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoGenero", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoGenero> createBeneficiariosDTOTipoGenero(TipoGenero value) {
        return new JAXBElement<TipoGenero>(_BeneficiariosDTOTipoGenero_QNAME, TipoGenero.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoFechaNacimiento", scope = BeneficiariosDTO.class)
    public JAXBElement<XMLGregorianCalendar> createBeneficiariosDTOTipoFechaNacimiento(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_BeneficiariosDTOTipoFechaNacimiento_QNAME, XMLGregorianCalendar.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIndEstudiaAct }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoIndEstudiaAct }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoIndEstudiaAct", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoIndEstudiaAct> createBeneficiariosDTOTipoIndEstudiaAct(TipoIndEstudiaAct value) {
        return new JAXBElement<TipoIndEstudiaAct>(_BeneficiariosDTOTipoIndEstudiaAct_QNAME, TipoIndEstudiaAct.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIndDependeEco }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoIndDependeEco }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoIndDependeEco", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoIndDependeEco> createBeneficiariosDTOTipoIndDependeEco(TipoIndDependeEco value) {
        return new JAXBElement<TipoIndDependeEco>(_BeneficiariosDTOTipoIndDependeEco_QNAME, TipoIndDependeEco.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoEstadoExpedicion }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoEstadoExpedicion }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoEstadoExpedicion", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoEstadoExpedicion> createBeneficiariosDTOTipoEstadoExpedicion(TipoEstadoExpedicion value) {
        return new JAXBElement<TipoEstadoExpedicion>(_BeneficiariosDTOTipoEstadoExpedicion_QNAME, TipoEstadoExpedicion.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoEstadoActual }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipoEstadoActual }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "tipoEstadoActual", scope = BeneficiariosDTO.class)
    public JAXBElement<TipoEstadoActual> createBeneficiariosDTOTipoEstadoActual(TipoEstadoActual value) {
        return new JAXBElement<TipoEstadoActual>(_BeneficiariosDTOTipoEstadoActual_QNAME, TipoEstadoActual.class, BeneficiariosDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemporBeneficiario }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TemporBeneficiario }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/BeneficiariosDTO", name = "temporBeneficiario", scope = BeneficiariosDTO.class)
    public JAXBElement<TemporBeneficiario> createBeneficiariosDTOTemporBeneficiario(TemporBeneficiario value) {
        return new JAXBElement<TemporBeneficiario>(_BeneficiariosDTOTemporBeneficiario_QNAME, TemporBeneficiario.class, BeneficiariosDTO.class, value);
    }

}
