//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/ResultadoDTO", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bbva.obp.SolicitudRentas.wsdl;
