//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistroNovedad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroNovedad"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoIdentificacionCausante" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroNovedad}TipoIdentificacionCausante"/&gt;
 *         &lt;element name="tipoDocumentoCausante" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tiponovedad" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO}NovedadRentaDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroNovedad", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroNovedad", propOrder = {
    "tipoIdentificacionCausante",
    "tipoDocumentoCausante",
    "tiponovedad"
})
public class RegistroNovedad {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoIdentificacionCausante tipoIdentificacionCausante;
    @XmlElement(required = true)
    protected String tipoDocumentoCausante;
    @XmlElement(required = true)
    protected NovedadRentaDTO tiponovedad;

    /**
     * Gets the value of the tipoIdentificacionCausante property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacionCausante }
     *     
     */
    public TipoIdentificacionCausante getTipoIdentificacionCausante() {
        return tipoIdentificacionCausante;
    }

    /**
     * Sets the value of the tipoIdentificacionCausante property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacionCausante }
     *     
     */
    public void setTipoIdentificacionCausante(TipoIdentificacionCausante value) {
        this.tipoIdentificacionCausante = value;
    }

    /**
     * Gets the value of the tipoDocumentoCausante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumentoCausante() {
        return tipoDocumentoCausante;
    }

    /**
     * Sets the value of the tipoDocumentoCausante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumentoCausante(String value) {
        this.tipoDocumentoCausante = value;
    }

    /**
     * Gets the value of the tiponovedad property.
     * 
     * @return
     *     possible object is
     *     {@link NovedadRentaDTO }
     *     
     */
    public NovedadRentaDTO getTiponovedad() {
        return tiponovedad;
    }

    /**
     * Sets the value of the tiponovedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link NovedadRentaDTO }
     *     
     */
    public void setTiponovedad(NovedadRentaDTO value) {
        this.tiponovedad = value;
    }

}
