//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RentaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RentaDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoNumeroPoliza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoFechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="tipoFechaDerecho" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="tipoInteresTecnico" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoOrigenPrestacion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO}TipoOrigenPrestacion"/&gt;
 *         &lt;element name="tipoModalidadPrestacion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO}TipoModalidadPrestacion"/&gt;
 *         &lt;element name="tipoFechaInicioRenDif" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="tipoAfpVen" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="tipoValorMesada" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoNumeroMesadas" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="tipoValorReservaInVe" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoValorReservaSob" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoValorReservaAux" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoValorOtrReserva" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoGastosAdmon" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoValorTotRes" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="docSoporteJudicial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fechaDocSopteJud" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="observacionesFalloJud" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RentaDTO", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", propOrder = {
    "tipoNumeroPoliza",
    "tipoFechaExpedicion",
    "tipoFechaDerecho",
    "tipoInteresTecnico",
    "tipoOrigenPrestacion",
    "tipoModalidadPrestacion",
    "tipoFechaInicioRenDif",
    "tipoAfpVen",
    "tipoValorMesada",
    "tipoNumeroMesadas",
    "tipoValorReservaInVe",
    "tipoValorReservaSob",
    "tipoValorReservaAux",
    "tipoValorOtrReserva",
    "tipoGastosAdmon",
    "tipoValorTotRes",
    "docSoporteJudicial",
    "fechaDocSopteJud",
    "observacionesFalloJud"
})
public class RentaDTO {

    @XmlElement(required = true)
    protected String tipoNumeroPoliza;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tipoFechaExpedicion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tipoFechaDerecho;
    @XmlElement(required = true)
    protected BigDecimal tipoInteresTecnico;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoOrigenPrestacion tipoOrigenPrestacion;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TipoModalidadPrestacion tipoModalidadPrestacion;
    @XmlElementRef(name = "tipoFechaInicioRenDif", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> tipoFechaInicioRenDif;
    protected int tipoAfpVen;
    @XmlElement(required = true)
    protected BigDecimal tipoValorMesada;
    protected int tipoNumeroMesadas;
    @XmlElement(required = true)
    protected BigDecimal tipoValorReservaInVe;
    @XmlElement(required = true)
    protected BigDecimal tipoValorReservaSob;
    @XmlElement(required = true)
    protected BigDecimal tipoValorReservaAux;
    @XmlElement(required = true)
    protected BigDecimal tipoValorOtrReserva;
    @XmlElement(required = true)
    protected BigDecimal tipoGastosAdmon;
    @XmlElement(required = true)
    protected BigDecimal tipoValorTotRes;
    @XmlElementRef(name = "docSoporteJudicial", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> docSoporteJudicial;
    @XmlElementRef(name = "fechaDocSopteJud", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> fechaDocSopteJud;
    @XmlElementRef(name = "observacionesFalloJud", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RentaDTO", type = JAXBElement.class, required = false)
    protected JAXBElement<String> observacionesFalloJud;

    /**
     * Gets the value of the tipoNumeroPoliza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoNumeroPoliza() {
        return tipoNumeroPoliza;
    }

    /**
     * Sets the value of the tipoNumeroPoliza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoNumeroPoliza(String value) {
        this.tipoNumeroPoliza = value;
    }

    /**
     * Gets the value of the tipoFechaExpedicion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTipoFechaExpedicion() {
        return tipoFechaExpedicion;
    }

    /**
     * Sets the value of the tipoFechaExpedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTipoFechaExpedicion(XMLGregorianCalendar value) {
        this.tipoFechaExpedicion = value;
    }

    /**
     * Gets the value of the tipoFechaDerecho property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTipoFechaDerecho() {
        return tipoFechaDerecho;
    }

    /**
     * Sets the value of the tipoFechaDerecho property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTipoFechaDerecho(XMLGregorianCalendar value) {
        this.tipoFechaDerecho = value;
    }

    /**
     * Gets the value of the tipoInteresTecnico property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoInteresTecnico() {
        return tipoInteresTecnico;
    }

    /**
     * Sets the value of the tipoInteresTecnico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoInteresTecnico(BigDecimal value) {
        this.tipoInteresTecnico = value;
    }

    /**
     * Gets the value of the tipoOrigenPrestacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOrigenPrestacion }
     *     
     */
    public TipoOrigenPrestacion getTipoOrigenPrestacion() {
        return tipoOrigenPrestacion;
    }

    /**
     * Sets the value of the tipoOrigenPrestacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOrigenPrestacion }
     *     
     */
    public void setTipoOrigenPrestacion(TipoOrigenPrestacion value) {
        this.tipoOrigenPrestacion = value;
    }

    /**
     * Gets the value of the tipoModalidadPrestacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoModalidadPrestacion }
     *     
     */
    public TipoModalidadPrestacion getTipoModalidadPrestacion() {
        return tipoModalidadPrestacion;
    }

    /**
     * Sets the value of the tipoModalidadPrestacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoModalidadPrestacion }
     *     
     */
    public void setTipoModalidadPrestacion(TipoModalidadPrestacion value) {
        this.tipoModalidadPrestacion = value;
    }

    /**
     * Gets the value of the tipoFechaInicioRenDif property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTipoFechaInicioRenDif() {
        return tipoFechaInicioRenDif;
    }

    /**
     * Sets the value of the tipoFechaInicioRenDif property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTipoFechaInicioRenDif(JAXBElement<XMLGregorianCalendar> value) {
        this.tipoFechaInicioRenDif = value;
    }

    /**
     * Gets the value of the tipoAfpVen property.
     * 
     */
    public int getTipoAfpVen() {
        return tipoAfpVen;
    }

    /**
     * Sets the value of the tipoAfpVen property.
     * 
     */
    public void setTipoAfpVen(int value) {
        this.tipoAfpVen = value;
    }

    /**
     * Gets the value of the tipoValorMesada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorMesada() {
        return tipoValorMesada;
    }

    /**
     * Sets the value of the tipoValorMesada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorMesada(BigDecimal value) {
        this.tipoValorMesada = value;
    }

    /**
     * Gets the value of the tipoNumeroMesadas property.
     * 
     */
    public int getTipoNumeroMesadas() {
        return tipoNumeroMesadas;
    }

    /**
     * Sets the value of the tipoNumeroMesadas property.
     * 
     */
    public void setTipoNumeroMesadas(int value) {
        this.tipoNumeroMesadas = value;
    }

    /**
     * Gets the value of the tipoValorReservaInVe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorReservaInVe() {
        return tipoValorReservaInVe;
    }

    /**
     * Sets the value of the tipoValorReservaInVe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorReservaInVe(BigDecimal value) {
        this.tipoValorReservaInVe = value;
    }

    /**
     * Gets the value of the tipoValorReservaSob property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorReservaSob() {
        return tipoValorReservaSob;
    }

    /**
     * Sets the value of the tipoValorReservaSob property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorReservaSob(BigDecimal value) {
        this.tipoValorReservaSob = value;
    }

    /**
     * Gets the value of the tipoValorReservaAux property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorReservaAux() {
        return tipoValorReservaAux;
    }

    /**
     * Sets the value of the tipoValorReservaAux property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorReservaAux(BigDecimal value) {
        this.tipoValorReservaAux = value;
    }

    /**
     * Gets the value of the tipoValorOtrReserva property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorOtrReserva() {
        return tipoValorOtrReserva;
    }

    /**
     * Sets the value of the tipoValorOtrReserva property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorOtrReserva(BigDecimal value) {
        this.tipoValorOtrReserva = value;
    }

    /**
     * Gets the value of the tipoGastosAdmon property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoGastosAdmon() {
        return tipoGastosAdmon;
    }

    /**
     * Sets the value of the tipoGastosAdmon property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoGastosAdmon(BigDecimal value) {
        this.tipoGastosAdmon = value;
    }

    /**
     * Gets the value of the tipoValorTotRes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTipoValorTotRes() {
        return tipoValorTotRes;
    }

    /**
     * Sets the value of the tipoValorTotRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTipoValorTotRes(BigDecimal value) {
        this.tipoValorTotRes = value;
    }

    /**
     * Gets the value of the docSoporteJudicial property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDocSoporteJudicial() {
        return docSoporteJudicial;
    }

    /**
     * Sets the value of the docSoporteJudicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDocSoporteJudicial(JAXBElement<String> value) {
        this.docSoporteJudicial = value;
    }

    /**
     * Gets the value of the fechaDocSopteJud property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getFechaDocSopteJud() {
        return fechaDocSopteJud;
    }

    /**
     * Sets the value of the fechaDocSopteJud property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setFechaDocSopteJud(JAXBElement<XMLGregorianCalendar> value) {
        this.fechaDocSopteJud = value;
    }

    /**
     * Gets the value of the observacionesFalloJud property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getObservacionesFalloJud() {
        return observacionesFalloJud;
    }

    /**
     * Sets the value of the observacionesFalloJud property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setObservacionesFalloJud(JAXBElement<String> value) {
        this.observacionesFalloJud = value;
    }

}
