//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultadoDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultadoDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tipoCodigoTransaccion" type="{http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/ResultadoDTO}TipoCodigoTransaccionE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultadoDTO", propOrder = {
    "tipoCodigoTransaccion"
})
public class ResultadoDTO {

    @XmlElement(required = true)
    protected TipoCodigoTransaccionE tipoCodigoTransaccion;

    /**
     * Gets the value of the tipoCodigoTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigoTransaccionE }
     *     
     */
    public TipoCodigoTransaccionE getTipoCodigoTransaccion() {
        return tipoCodigoTransaccion;
    }

    /**
     * Sets the value of the tipoCodigoTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigoTransaccionE }
     *     
     */
    public void setTipoCodigoTransaccion(TipoCodigoTransaccionE value) {
        this.tipoCodigoTransaccion = value;
    }

}
