//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoDocumento.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TipoDocumento"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CONT"/&gt;
 *     &lt;enumeration value="FLMS"/&gt;
 *     &lt;enumeration value="DOCI"/&gt;
 *     &lt;enumeration value="ACIN"/&gt;
 *     &lt;enumeration value="ACDE"/&gt;
 *     &lt;enumeration value="DSPL"/&gt;
 *     &lt;enumeration value="CERE"/&gt;
 *     &lt;enumeration value="DDEP"/&gt;
 *     &lt;enumeration value="RCIV"/&gt;
 *     &lt;enumeration value="RCMA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TipoDocumento", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/RegistroDocumentos")
@XmlEnum
public enum TipoDocumento {

    CONT,
    FLMS,
    DOCI,
    ACIN,
    ACDE,
    DSPL,
    CERE,
    DDEP,
    RCIV,
    RCMA;

    public String value() {
        return name();
    }

    public static TipoDocumento fromValue(String v) {
        return valueOf(v);
    }

}
