//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.12 at 10:24:31 AM COT 
//


package com.bbva.obp.SolicitudRentas.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoNovedad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TipoNovedad"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FA"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="PD"/&gt;
 *     &lt;enumeration value="IM"/&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="AD"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TipoNovedad", namespace = "http://servicios.webservices.bonospensionales.minhacienda.gov.co/schema/NovedadRentaDTO")
@XmlEnum
public enum TipoNovedad {

    FA,
    IN,
    PD,
    IM,
    NB,
    AD,
    CM;

    public String value() {
        return name();
    }

    public static TipoNovedad fromValue(String v) {
        return valueOf(v);
    }

}
